"""Find Windows PE entrypoint anomalies.

Checks for anomalies in the section the entry point is in, namely
 - The entry point section should not be the last section
 - The entry point section should have a standard name like ".text"

"""

from __future__ import annotations

import pefile
from azul_runner import BinaryPlugin, Feature, Job, State, add_settings, cmdline_run


class AzulPluginEntryPointCheck(BinaryPlugin):
    """Find Windows PE entrypoint anomalies."""

    CONTACT = "ASD's ACSC"
    VERSION = "2025.03.18"
    SETTINGS = add_settings(
        filter_data_types={
            "content": [
                # Windows exe
                "executable/windows/pe",
                "executable/windows/pe32",
                "executable/windows/pe64",
                "executable/windows/dll",
                "executable/windows/dll32",
                "executable/windows/dll64",
                # Non windows exe
                "executable/dll32",
                "executable/pe32",
            ]
        },
    )
    FEATURES = [Feature(name="tag", desc="Tags generated by PE entrypoint check", type=str)]

    def execute(self, job: Job):
        """Execute the plugin across all windows executables with content."""
        try:
            pe = pefile.PE(job.get_data().get_filepath())

            if not pe.sections:
                return self.is_malformed("No sections parsed from PE File")
        except (pefile.PEFormatError, ValueError, AttributeError) as e:
            return State(
                State.Label.ERROR_EXCEPTION,
                failure_name="pefile parse error",
                message=str(e.args[0]) if e.args else "",
            )

        ep = pe.NT_HEADERS.OPTIONAL_HEADER.AddressOfEntryPoint
        eps = pe.sections[0]
        last_physical = pe.sections[0]
        last_virtual = pe.sections[0]
        entry_point_section_names = [b".text", b"INIT", b"UPX1"]

        for s in pe.sections:
            # Find which section AddressOfEntryPoint points at
            if ep >= s.VirtualAddress:
                eps = s

            # Find the last section in memory
            if last_virtual.VirtualAddress < s.VirtualAddress:
                last_virtual = s

            # Find the last section on disk
            if last_physical.PointerToRawData < s.PointerToRawData:
                last_physical = s

        name = eps.Name.strip(b"\x00")
        tags = []
        if name not in entry_point_section_names:
            tags.append("Entrypoint points to nonstandard section")

        if eps == last_physical:
            tags.append("Entrypoint is last section")

        # If either of the following are true, the previously set tags make no
        # sense - so we overwrite them
        if ep > (last_virtual.VirtualAddress + last_virtual.SizeOfRawData):
            tags = ["Entrypoint outside valid range"]

        if ep < len(pe.header):
            tags = ["Entrypoint points to PE Header"]
        if tags:
            self.add_feature_values("tag", tags)


def main():
    """Run plugin via command-line."""
    cmdline_run(plugin=AzulPluginEntryPointCheck)


if __name__ == "__main__":
    main()
